//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace FrontEnd.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebService1Soap", Namespace="http://tempuri.org/")]
    public partial class WebService1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback FazerLoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback inserirUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback listarUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback alterarUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback deletarUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback inserirClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback listarClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback alterClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback deletarClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback inserirEspecieOperationCompleted;
        
        private System.Threading.SendOrPostCallback listarEspecieOperationCompleted;
        
        private System.Threading.SendOrPostCallback alterarEspecieOperationCompleted;
        
        private System.Threading.SendOrPostCallback deletarEspecieOperationCompleted;
        
        private System.Threading.SendOrPostCallback inserirAnimalOperationCompleted;
        
        private System.Threading.SendOrPostCallback listarAnimalOperationCompleted;
        
        private System.Threading.SendOrPostCallback AlterarAnimalOperationCompleted;
        
        private System.Threading.SendOrPostCallback deletarAnimalOperationCompleted;
        
        private System.Threading.SendOrPostCallback inserirCorOperationCompleted;
        
        private System.Threading.SendOrPostCallback listarCorOperationCompleted;
        
        private System.Threading.SendOrPostCallback AlterarCarOperationCompleted;
        
        private System.Threading.SendOrPostCallback deletarCorOperationCompleted;
        
        private System.Threading.SendOrPostCallback insertRacaOperationCompleted;
        
        private System.Threading.SendOrPostCallback listarRacaOperationCompleted;
        
        private System.Threading.SendOrPostCallback AlterarRacaOperationCompleted;
        
        private System.Threading.SendOrPostCallback deletarRacaOperationCompleted;
        
        private System.Threading.SendOrPostCallback insertCliente_AnimalOperationCompleted;
        
        private System.Threading.SendOrPostCallback listarCliente_AnimalOperationCompleted;
        
        private System.Threading.SendOrPostCallback insertAnimal_CorOperationCompleted;
        
        private System.Threading.SendOrPostCallback listarAnimal_corOperationCompleted;
        
        private System.Threading.SendOrPostCallback insertAnimal_RacaOperationCompleted;
        
        private System.Threading.SendOrPostCallback listarAnimal_RacaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebService1() {
            this.Url = global::FrontEnd.Properties.Settings.Default.FrontEnd_localhost_WebService1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event FazerLoginCompletedEventHandler FazerLoginCompleted;
        
        /// <remarks/>
        public event inserirUsuarioCompletedEventHandler inserirUsuarioCompleted;
        
        /// <remarks/>
        public event listarUsuarioCompletedEventHandler listarUsuarioCompleted;
        
        /// <remarks/>
        public event alterarUsuarioCompletedEventHandler alterarUsuarioCompleted;
        
        /// <remarks/>
        public event deletarUsuarioCompletedEventHandler deletarUsuarioCompleted;
        
        /// <remarks/>
        public event inserirClienteCompletedEventHandler inserirClienteCompleted;
        
        /// <remarks/>
        public event listarClienteCompletedEventHandler listarClienteCompleted;
        
        /// <remarks/>
        public event alterClienteCompletedEventHandler alterClienteCompleted;
        
        /// <remarks/>
        public event deletarClienteCompletedEventHandler deletarClienteCompleted;
        
        /// <remarks/>
        public event inserirEspecieCompletedEventHandler inserirEspecieCompleted;
        
        /// <remarks/>
        public event listarEspecieCompletedEventHandler listarEspecieCompleted;
        
        /// <remarks/>
        public event alterarEspecieCompletedEventHandler alterarEspecieCompleted;
        
        /// <remarks/>
        public event deletarEspecieCompletedEventHandler deletarEspecieCompleted;
        
        /// <remarks/>
        public event inserirAnimalCompletedEventHandler inserirAnimalCompleted;
        
        /// <remarks/>
        public event listarAnimalCompletedEventHandler listarAnimalCompleted;
        
        /// <remarks/>
        public event AlterarAnimalCompletedEventHandler AlterarAnimalCompleted;
        
        /// <remarks/>
        public event deletarAnimalCompletedEventHandler deletarAnimalCompleted;
        
        /// <remarks/>
        public event inserirCorCompletedEventHandler inserirCorCompleted;
        
        /// <remarks/>
        public event listarCorCompletedEventHandler listarCorCompleted;
        
        /// <remarks/>
        public event AlterarCarCompletedEventHandler AlterarCarCompleted;
        
        /// <remarks/>
        public event deletarCorCompletedEventHandler deletarCorCompleted;
        
        /// <remarks/>
        public event insertRacaCompletedEventHandler insertRacaCompleted;
        
        /// <remarks/>
        public event listarRacaCompletedEventHandler listarRacaCompleted;
        
        /// <remarks/>
        public event AlterarRacaCompletedEventHandler AlterarRacaCompleted;
        
        /// <remarks/>
        public event deletarRacaCompletedEventHandler deletarRacaCompleted;
        
        /// <remarks/>
        public event insertCliente_AnimalCompletedEventHandler insertCliente_AnimalCompleted;
        
        /// <remarks/>
        public event listarCliente_AnimalCompletedEventHandler listarCliente_AnimalCompleted;
        
        /// <remarks/>
        public event insertAnimal_CorCompletedEventHandler insertAnimal_CorCompleted;
        
        /// <remarks/>
        public event listarAnimal_corCompletedEventHandler listarAnimal_corCompleted;
        
        /// <remarks/>
        public event insertAnimal_RacaCompletedEventHandler insertAnimal_RacaCompleted;
        
        /// <remarks/>
        public event listarAnimal_RacaCompletedEventHandler listarAnimal_RacaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FazerLogin", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Usuario FazerLogin(string login, string senha) {
            object[] results = this.Invoke("FazerLogin", new object[] {
                        login,
                        senha});
            return ((Usuario)(results[0]));
        }
        
        /// <remarks/>
        public void FazerLoginAsync(string login, string senha) {
            this.FazerLoginAsync(login, senha, null);
        }
        
        /// <remarks/>
        public void FazerLoginAsync(string login, string senha, object userState) {
            if ((this.FazerLoginOperationCompleted == null)) {
                this.FazerLoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFazerLoginOperationCompleted);
            }
            this.InvokeAsync("FazerLogin", new object[] {
                        login,
                        senha}, this.FazerLoginOperationCompleted, userState);
        }
        
        private void OnFazerLoginOperationCompleted(object arg) {
            if ((this.FazerLoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FazerLoginCompleted(this, new FazerLoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/inserirUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Usuario inserirUsuario(Usuario usuario) {
            object[] results = this.Invoke("inserirUsuario", new object[] {
                        usuario});
            return ((Usuario)(results[0]));
        }
        
        /// <remarks/>
        public void inserirUsuarioAsync(Usuario usuario) {
            this.inserirUsuarioAsync(usuario, null);
        }
        
        /// <remarks/>
        public void inserirUsuarioAsync(Usuario usuario, object userState) {
            if ((this.inserirUsuarioOperationCompleted == null)) {
                this.inserirUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OninserirUsuarioOperationCompleted);
            }
            this.InvokeAsync("inserirUsuario", new object[] {
                        usuario}, this.inserirUsuarioOperationCompleted, userState);
        }
        
        private void OninserirUsuarioOperationCompleted(object arg) {
            if ((this.inserirUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.inserirUsuarioCompleted(this, new inserirUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/listarUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Usuario[] listarUsuario() {
            object[] results = this.Invoke("listarUsuario", new object[0]);
            return ((Usuario[])(results[0]));
        }
        
        /// <remarks/>
        public void listarUsuarioAsync() {
            this.listarUsuarioAsync(null);
        }
        
        /// <remarks/>
        public void listarUsuarioAsync(object userState) {
            if ((this.listarUsuarioOperationCompleted == null)) {
                this.listarUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistarUsuarioOperationCompleted);
            }
            this.InvokeAsync("listarUsuario", new object[0], this.listarUsuarioOperationCompleted, userState);
        }
        
        private void OnlistarUsuarioOperationCompleted(object arg) {
            if ((this.listarUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listarUsuarioCompleted(this, new listarUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/alterarUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void alterarUsuario(Usuario usuario) {
            this.Invoke("alterarUsuario", new object[] {
                        usuario});
        }
        
        /// <remarks/>
        public void alterarUsuarioAsync(Usuario usuario) {
            this.alterarUsuarioAsync(usuario, null);
        }
        
        /// <remarks/>
        public void alterarUsuarioAsync(Usuario usuario, object userState) {
            if ((this.alterarUsuarioOperationCompleted == null)) {
                this.alterarUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnalterarUsuarioOperationCompleted);
            }
            this.InvokeAsync("alterarUsuario", new object[] {
                        usuario}, this.alterarUsuarioOperationCompleted, userState);
        }
        
        private void OnalterarUsuarioOperationCompleted(object arg) {
            if ((this.alterarUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.alterarUsuarioCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/deletarUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void deletarUsuario(Usuario usuario) {
            this.Invoke("deletarUsuario", new object[] {
                        usuario});
        }
        
        /// <remarks/>
        public void deletarUsuarioAsync(Usuario usuario) {
            this.deletarUsuarioAsync(usuario, null);
        }
        
        /// <remarks/>
        public void deletarUsuarioAsync(Usuario usuario, object userState) {
            if ((this.deletarUsuarioOperationCompleted == null)) {
                this.deletarUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeletarUsuarioOperationCompleted);
            }
            this.InvokeAsync("deletarUsuario", new object[] {
                        usuario}, this.deletarUsuarioOperationCompleted, userState);
        }
        
        private void OndeletarUsuarioOperationCompleted(object arg) {
            if ((this.deletarUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deletarUsuarioCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/inserirCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void inserirCliente(Cliente cliente) {
            this.Invoke("inserirCliente", new object[] {
                        cliente});
        }
        
        /// <remarks/>
        public void inserirClienteAsync(Cliente cliente) {
            this.inserirClienteAsync(cliente, null);
        }
        
        /// <remarks/>
        public void inserirClienteAsync(Cliente cliente, object userState) {
            if ((this.inserirClienteOperationCompleted == null)) {
                this.inserirClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OninserirClienteOperationCompleted);
            }
            this.InvokeAsync("inserirCliente", new object[] {
                        cliente}, this.inserirClienteOperationCompleted, userState);
        }
        
        private void OninserirClienteOperationCompleted(object arg) {
            if ((this.inserirClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.inserirClienteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/listarCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Cliente[] listarCliente() {
            object[] results = this.Invoke("listarCliente", new object[0]);
            return ((Cliente[])(results[0]));
        }
        
        /// <remarks/>
        public void listarClienteAsync() {
            this.listarClienteAsync(null);
        }
        
        /// <remarks/>
        public void listarClienteAsync(object userState) {
            if ((this.listarClienteOperationCompleted == null)) {
                this.listarClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistarClienteOperationCompleted);
            }
            this.InvokeAsync("listarCliente", new object[0], this.listarClienteOperationCompleted, userState);
        }
        
        private void OnlistarClienteOperationCompleted(object arg) {
            if ((this.listarClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listarClienteCompleted(this, new listarClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/alterCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void alterCliente(Cliente cliente) {
            this.Invoke("alterCliente", new object[] {
                        cliente});
        }
        
        /// <remarks/>
        public void alterClienteAsync(Cliente cliente) {
            this.alterClienteAsync(cliente, null);
        }
        
        /// <remarks/>
        public void alterClienteAsync(Cliente cliente, object userState) {
            if ((this.alterClienteOperationCompleted == null)) {
                this.alterClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnalterClienteOperationCompleted);
            }
            this.InvokeAsync("alterCliente", new object[] {
                        cliente}, this.alterClienteOperationCompleted, userState);
        }
        
        private void OnalterClienteOperationCompleted(object arg) {
            if ((this.alterClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.alterClienteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/deletarCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void deletarCliente(Cliente cliente) {
            this.Invoke("deletarCliente", new object[] {
                        cliente});
        }
        
        /// <remarks/>
        public void deletarClienteAsync(Cliente cliente) {
            this.deletarClienteAsync(cliente, null);
        }
        
        /// <remarks/>
        public void deletarClienteAsync(Cliente cliente, object userState) {
            if ((this.deletarClienteOperationCompleted == null)) {
                this.deletarClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeletarClienteOperationCompleted);
            }
            this.InvokeAsync("deletarCliente", new object[] {
                        cliente}, this.deletarClienteOperationCompleted, userState);
        }
        
        private void OndeletarClienteOperationCompleted(object arg) {
            if ((this.deletarClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deletarClienteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/inserirEspecie", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void inserirEspecie(Especie especie) {
            this.Invoke("inserirEspecie", new object[] {
                        especie});
        }
        
        /// <remarks/>
        public void inserirEspecieAsync(Especie especie) {
            this.inserirEspecieAsync(especie, null);
        }
        
        /// <remarks/>
        public void inserirEspecieAsync(Especie especie, object userState) {
            if ((this.inserirEspecieOperationCompleted == null)) {
                this.inserirEspecieOperationCompleted = new System.Threading.SendOrPostCallback(this.OninserirEspecieOperationCompleted);
            }
            this.InvokeAsync("inserirEspecie", new object[] {
                        especie}, this.inserirEspecieOperationCompleted, userState);
        }
        
        private void OninserirEspecieOperationCompleted(object arg) {
            if ((this.inserirEspecieCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.inserirEspecieCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/listarEspecie", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Especie[] listarEspecie() {
            object[] results = this.Invoke("listarEspecie", new object[0]);
            return ((Especie[])(results[0]));
        }
        
        /// <remarks/>
        public void listarEspecieAsync() {
            this.listarEspecieAsync(null);
        }
        
        /// <remarks/>
        public void listarEspecieAsync(object userState) {
            if ((this.listarEspecieOperationCompleted == null)) {
                this.listarEspecieOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistarEspecieOperationCompleted);
            }
            this.InvokeAsync("listarEspecie", new object[0], this.listarEspecieOperationCompleted, userState);
        }
        
        private void OnlistarEspecieOperationCompleted(object arg) {
            if ((this.listarEspecieCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listarEspecieCompleted(this, new listarEspecieCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/alterarEspecie", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void alterarEspecie(Especie especie) {
            this.Invoke("alterarEspecie", new object[] {
                        especie});
        }
        
        /// <remarks/>
        public void alterarEspecieAsync(Especie especie) {
            this.alterarEspecieAsync(especie, null);
        }
        
        /// <remarks/>
        public void alterarEspecieAsync(Especie especie, object userState) {
            if ((this.alterarEspecieOperationCompleted == null)) {
                this.alterarEspecieOperationCompleted = new System.Threading.SendOrPostCallback(this.OnalterarEspecieOperationCompleted);
            }
            this.InvokeAsync("alterarEspecie", new object[] {
                        especie}, this.alterarEspecieOperationCompleted, userState);
        }
        
        private void OnalterarEspecieOperationCompleted(object arg) {
            if ((this.alterarEspecieCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.alterarEspecieCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/deletarEspecie", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void deletarEspecie(Especie especie) {
            this.Invoke("deletarEspecie", new object[] {
                        especie});
        }
        
        /// <remarks/>
        public void deletarEspecieAsync(Especie especie) {
            this.deletarEspecieAsync(especie, null);
        }
        
        /// <remarks/>
        public void deletarEspecieAsync(Especie especie, object userState) {
            if ((this.deletarEspecieOperationCompleted == null)) {
                this.deletarEspecieOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeletarEspecieOperationCompleted);
            }
            this.InvokeAsync("deletarEspecie", new object[] {
                        especie}, this.deletarEspecieOperationCompleted, userState);
        }
        
        private void OndeletarEspecieOperationCompleted(object arg) {
            if ((this.deletarEspecieCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deletarEspecieCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/inserirAnimal", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void inserirAnimal(Animal animal) {
            this.Invoke("inserirAnimal", new object[] {
                        animal});
        }
        
        /// <remarks/>
        public void inserirAnimalAsync(Animal animal) {
            this.inserirAnimalAsync(animal, null);
        }
        
        /// <remarks/>
        public void inserirAnimalAsync(Animal animal, object userState) {
            if ((this.inserirAnimalOperationCompleted == null)) {
                this.inserirAnimalOperationCompleted = new System.Threading.SendOrPostCallback(this.OninserirAnimalOperationCompleted);
            }
            this.InvokeAsync("inserirAnimal", new object[] {
                        animal}, this.inserirAnimalOperationCompleted, userState);
        }
        
        private void OninserirAnimalOperationCompleted(object arg) {
            if ((this.inserirAnimalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.inserirAnimalCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/listarAnimal", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Animal[] listarAnimal() {
            object[] results = this.Invoke("listarAnimal", new object[0]);
            return ((Animal[])(results[0]));
        }
        
        /// <remarks/>
        public void listarAnimalAsync() {
            this.listarAnimalAsync(null);
        }
        
        /// <remarks/>
        public void listarAnimalAsync(object userState) {
            if ((this.listarAnimalOperationCompleted == null)) {
                this.listarAnimalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistarAnimalOperationCompleted);
            }
            this.InvokeAsync("listarAnimal", new object[0], this.listarAnimalOperationCompleted, userState);
        }
        
        private void OnlistarAnimalOperationCompleted(object arg) {
            if ((this.listarAnimalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listarAnimalCompleted(this, new listarAnimalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AlterarAnimal", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AlterarAnimal(Animal animal) {
            this.Invoke("AlterarAnimal", new object[] {
                        animal});
        }
        
        /// <remarks/>
        public void AlterarAnimalAsync(Animal animal) {
            this.AlterarAnimalAsync(animal, null);
        }
        
        /// <remarks/>
        public void AlterarAnimalAsync(Animal animal, object userState) {
            if ((this.AlterarAnimalOperationCompleted == null)) {
                this.AlterarAnimalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAlterarAnimalOperationCompleted);
            }
            this.InvokeAsync("AlterarAnimal", new object[] {
                        animal}, this.AlterarAnimalOperationCompleted, userState);
        }
        
        private void OnAlterarAnimalOperationCompleted(object arg) {
            if ((this.AlterarAnimalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AlterarAnimalCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/deletarAnimal", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void deletarAnimal(Animal animal) {
            this.Invoke("deletarAnimal", new object[] {
                        animal});
        }
        
        /// <remarks/>
        public void deletarAnimalAsync(Animal animal) {
            this.deletarAnimalAsync(animal, null);
        }
        
        /// <remarks/>
        public void deletarAnimalAsync(Animal animal, object userState) {
            if ((this.deletarAnimalOperationCompleted == null)) {
                this.deletarAnimalOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeletarAnimalOperationCompleted);
            }
            this.InvokeAsync("deletarAnimal", new object[] {
                        animal}, this.deletarAnimalOperationCompleted, userState);
        }
        
        private void OndeletarAnimalOperationCompleted(object arg) {
            if ((this.deletarAnimalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deletarAnimalCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/inserirCor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void inserirCor(Cor cor) {
            this.Invoke("inserirCor", new object[] {
                        cor});
        }
        
        /// <remarks/>
        public void inserirCorAsync(Cor cor) {
            this.inserirCorAsync(cor, null);
        }
        
        /// <remarks/>
        public void inserirCorAsync(Cor cor, object userState) {
            if ((this.inserirCorOperationCompleted == null)) {
                this.inserirCorOperationCompleted = new System.Threading.SendOrPostCallback(this.OninserirCorOperationCompleted);
            }
            this.InvokeAsync("inserirCor", new object[] {
                        cor}, this.inserirCorOperationCompleted, userState);
        }
        
        private void OninserirCorOperationCompleted(object arg) {
            if ((this.inserirCorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.inserirCorCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/listarCor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Cor[] listarCor() {
            object[] results = this.Invoke("listarCor", new object[0]);
            return ((Cor[])(results[0]));
        }
        
        /// <remarks/>
        public void listarCorAsync() {
            this.listarCorAsync(null);
        }
        
        /// <remarks/>
        public void listarCorAsync(object userState) {
            if ((this.listarCorOperationCompleted == null)) {
                this.listarCorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistarCorOperationCompleted);
            }
            this.InvokeAsync("listarCor", new object[0], this.listarCorOperationCompleted, userState);
        }
        
        private void OnlistarCorOperationCompleted(object arg) {
            if ((this.listarCorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listarCorCompleted(this, new listarCorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AlterarCar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AlterarCar(Cor cor) {
            this.Invoke("AlterarCar", new object[] {
                        cor});
        }
        
        /// <remarks/>
        public void AlterarCarAsync(Cor cor) {
            this.AlterarCarAsync(cor, null);
        }
        
        /// <remarks/>
        public void AlterarCarAsync(Cor cor, object userState) {
            if ((this.AlterarCarOperationCompleted == null)) {
                this.AlterarCarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAlterarCarOperationCompleted);
            }
            this.InvokeAsync("AlterarCar", new object[] {
                        cor}, this.AlterarCarOperationCompleted, userState);
        }
        
        private void OnAlterarCarOperationCompleted(object arg) {
            if ((this.AlterarCarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AlterarCarCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/deletarCor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void deletarCor(Cor cor) {
            this.Invoke("deletarCor", new object[] {
                        cor});
        }
        
        /// <remarks/>
        public void deletarCorAsync(Cor cor) {
            this.deletarCorAsync(cor, null);
        }
        
        /// <remarks/>
        public void deletarCorAsync(Cor cor, object userState) {
            if ((this.deletarCorOperationCompleted == null)) {
                this.deletarCorOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeletarCorOperationCompleted);
            }
            this.InvokeAsync("deletarCor", new object[] {
                        cor}, this.deletarCorOperationCompleted, userState);
        }
        
        private void OndeletarCorOperationCompleted(object arg) {
            if ((this.deletarCorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deletarCorCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/insertRaca", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void insertRaca(Raca raca) {
            this.Invoke("insertRaca", new object[] {
                        raca});
        }
        
        /// <remarks/>
        public void insertRacaAsync(Raca raca) {
            this.insertRacaAsync(raca, null);
        }
        
        /// <remarks/>
        public void insertRacaAsync(Raca raca, object userState) {
            if ((this.insertRacaOperationCompleted == null)) {
                this.insertRacaOperationCompleted = new System.Threading.SendOrPostCallback(this.OninsertRacaOperationCompleted);
            }
            this.InvokeAsync("insertRaca", new object[] {
                        raca}, this.insertRacaOperationCompleted, userState);
        }
        
        private void OninsertRacaOperationCompleted(object arg) {
            if ((this.insertRacaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.insertRacaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/listarRaca", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Raca[] listarRaca() {
            object[] results = this.Invoke("listarRaca", new object[0]);
            return ((Raca[])(results[0]));
        }
        
        /// <remarks/>
        public void listarRacaAsync() {
            this.listarRacaAsync(null);
        }
        
        /// <remarks/>
        public void listarRacaAsync(object userState) {
            if ((this.listarRacaOperationCompleted == null)) {
                this.listarRacaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistarRacaOperationCompleted);
            }
            this.InvokeAsync("listarRaca", new object[0], this.listarRacaOperationCompleted, userState);
        }
        
        private void OnlistarRacaOperationCompleted(object arg) {
            if ((this.listarRacaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listarRacaCompleted(this, new listarRacaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AlterarRaca", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AlterarRaca(Raca raca) {
            this.Invoke("AlterarRaca", new object[] {
                        raca});
        }
        
        /// <remarks/>
        public void AlterarRacaAsync(Raca raca) {
            this.AlterarRacaAsync(raca, null);
        }
        
        /// <remarks/>
        public void AlterarRacaAsync(Raca raca, object userState) {
            if ((this.AlterarRacaOperationCompleted == null)) {
                this.AlterarRacaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAlterarRacaOperationCompleted);
            }
            this.InvokeAsync("AlterarRaca", new object[] {
                        raca}, this.AlterarRacaOperationCompleted, userState);
        }
        
        private void OnAlterarRacaOperationCompleted(object arg) {
            if ((this.AlterarRacaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AlterarRacaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/deletarRaca", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void deletarRaca(Raca raca) {
            this.Invoke("deletarRaca", new object[] {
                        raca});
        }
        
        /// <remarks/>
        public void deletarRacaAsync(Raca raca) {
            this.deletarRacaAsync(raca, null);
        }
        
        /// <remarks/>
        public void deletarRacaAsync(Raca raca, object userState) {
            if ((this.deletarRacaOperationCompleted == null)) {
                this.deletarRacaOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeletarRacaOperationCompleted);
            }
            this.InvokeAsync("deletarRaca", new object[] {
                        raca}, this.deletarRacaOperationCompleted, userState);
        }
        
        private void OndeletarRacaOperationCompleted(object arg) {
            if ((this.deletarRacaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deletarRacaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/insertCliente_Animal", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void insertCliente_Animal(Cliente_Animal cliente_animal) {
            this.Invoke("insertCliente_Animal", new object[] {
                        cliente_animal});
        }
        
        /// <remarks/>
        public void insertCliente_AnimalAsync(Cliente_Animal cliente_animal) {
            this.insertCliente_AnimalAsync(cliente_animal, null);
        }
        
        /// <remarks/>
        public void insertCliente_AnimalAsync(Cliente_Animal cliente_animal, object userState) {
            if ((this.insertCliente_AnimalOperationCompleted == null)) {
                this.insertCliente_AnimalOperationCompleted = new System.Threading.SendOrPostCallback(this.OninsertCliente_AnimalOperationCompleted);
            }
            this.InvokeAsync("insertCliente_Animal", new object[] {
                        cliente_animal}, this.insertCliente_AnimalOperationCompleted, userState);
        }
        
        private void OninsertCliente_AnimalOperationCompleted(object arg) {
            if ((this.insertCliente_AnimalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.insertCliente_AnimalCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/listarCliente_Animal", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Cliente_Animal[] listarCliente_Animal() {
            object[] results = this.Invoke("listarCliente_Animal", new object[0]);
            return ((Cliente_Animal[])(results[0]));
        }
        
        /// <remarks/>
        public void listarCliente_AnimalAsync() {
            this.listarCliente_AnimalAsync(null);
        }
        
        /// <remarks/>
        public void listarCliente_AnimalAsync(object userState) {
            if ((this.listarCliente_AnimalOperationCompleted == null)) {
                this.listarCliente_AnimalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistarCliente_AnimalOperationCompleted);
            }
            this.InvokeAsync("listarCliente_Animal", new object[0], this.listarCliente_AnimalOperationCompleted, userState);
        }
        
        private void OnlistarCliente_AnimalOperationCompleted(object arg) {
            if ((this.listarCliente_AnimalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listarCliente_AnimalCompleted(this, new listarCliente_AnimalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/insertAnimal_Cor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void insertAnimal_Cor(Animal_Cor animal_cor) {
            this.Invoke("insertAnimal_Cor", new object[] {
                        animal_cor});
        }
        
        /// <remarks/>
        public void insertAnimal_CorAsync(Animal_Cor animal_cor) {
            this.insertAnimal_CorAsync(animal_cor, null);
        }
        
        /// <remarks/>
        public void insertAnimal_CorAsync(Animal_Cor animal_cor, object userState) {
            if ((this.insertAnimal_CorOperationCompleted == null)) {
                this.insertAnimal_CorOperationCompleted = new System.Threading.SendOrPostCallback(this.OninsertAnimal_CorOperationCompleted);
            }
            this.InvokeAsync("insertAnimal_Cor", new object[] {
                        animal_cor}, this.insertAnimal_CorOperationCompleted, userState);
        }
        
        private void OninsertAnimal_CorOperationCompleted(object arg) {
            if ((this.insertAnimal_CorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.insertAnimal_CorCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/listarAnimal_cor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Animal_Cor[] listarAnimal_cor() {
            object[] results = this.Invoke("listarAnimal_cor", new object[0]);
            return ((Animal_Cor[])(results[0]));
        }
        
        /// <remarks/>
        public void listarAnimal_corAsync() {
            this.listarAnimal_corAsync(null);
        }
        
        /// <remarks/>
        public void listarAnimal_corAsync(object userState) {
            if ((this.listarAnimal_corOperationCompleted == null)) {
                this.listarAnimal_corOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistarAnimal_corOperationCompleted);
            }
            this.InvokeAsync("listarAnimal_cor", new object[0], this.listarAnimal_corOperationCompleted, userState);
        }
        
        private void OnlistarAnimal_corOperationCompleted(object arg) {
            if ((this.listarAnimal_corCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listarAnimal_corCompleted(this, new listarAnimal_corCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/insertAnimal_Raca", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void insertAnimal_Raca(Animal_Raca animal_raca) {
            this.Invoke("insertAnimal_Raca", new object[] {
                        animal_raca});
        }
        
        /// <remarks/>
        public void insertAnimal_RacaAsync(Animal_Raca animal_raca) {
            this.insertAnimal_RacaAsync(animal_raca, null);
        }
        
        /// <remarks/>
        public void insertAnimal_RacaAsync(Animal_Raca animal_raca, object userState) {
            if ((this.insertAnimal_RacaOperationCompleted == null)) {
                this.insertAnimal_RacaOperationCompleted = new System.Threading.SendOrPostCallback(this.OninsertAnimal_RacaOperationCompleted);
            }
            this.InvokeAsync("insertAnimal_Raca", new object[] {
                        animal_raca}, this.insertAnimal_RacaOperationCompleted, userState);
        }
        
        private void OninsertAnimal_RacaOperationCompleted(object arg) {
            if ((this.insertAnimal_RacaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.insertAnimal_RacaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/listarAnimal_Raca", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Animal_Raca[] listarAnimal_Raca() {
            object[] results = this.Invoke("listarAnimal_Raca", new object[0]);
            return ((Animal_Raca[])(results[0]));
        }
        
        /// <remarks/>
        public void listarAnimal_RacaAsync() {
            this.listarAnimal_RacaAsync(null);
        }
        
        /// <remarks/>
        public void listarAnimal_RacaAsync(object userState) {
            if ((this.listarAnimal_RacaOperationCompleted == null)) {
                this.listarAnimal_RacaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistarAnimal_RacaOperationCompleted);
            }
            this.InvokeAsync("listarAnimal_Raca", new object[0], this.listarAnimal_RacaOperationCompleted, userState);
        }
        
        private void OnlistarAnimal_RacaOperationCompleted(object arg) {
            if ((this.listarAnimal_RacaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listarAnimal_RacaCompleted(this, new listarAnimal_RacaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Usuario {
        
        private int idField;
        
        private string nomeField;
        
        private string telefoneField;
        
        private string emailField;
        
        private string loginField;
        
        private string senhaField;
        
        private UsuarioTipo tipoField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public string Telefone {
            get {
                return this.telefoneField;
            }
            set {
                this.telefoneField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string Login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
            }
        }
        
        /// <remarks/>
        public string Senha {
            get {
                return this.senhaField;
            }
            set {
                this.senhaField = value;
            }
        }
        
        /// <remarks/>
        public UsuarioTipo Tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum UsuarioTipo {
        
        /// <remarks/>
        CLIENTE,
        
        /// <remarks/>
        VETERINARIO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Animal_Raca {
        
        private int idField;
        
        private Animal animal_idField;
        
        private Raca raca_idField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public Animal Animal_id {
            get {
                return this.animal_idField;
            }
            set {
                this.animal_idField = value;
            }
        }
        
        /// <remarks/>
        public Raca Raca_id {
            get {
                return this.raca_idField;
            }
            set {
                this.raca_idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Animal {
        
        private int idField;
        
        private Especie especieField;
        
        private int idadeField;
        
        private string nomeField;
        
        private float pesoField;
        
        private string corField;
        
        private string racaField;
        
        private System.DateTime dataCadastroField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public Especie Especie {
            get {
                return this.especieField;
            }
            set {
                this.especieField = value;
            }
        }
        
        /// <remarks/>
        public int Idade {
            get {
                return this.idadeField;
            }
            set {
                this.idadeField = value;
            }
        }
        
        /// <remarks/>
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public float Peso {
            get {
                return this.pesoField;
            }
            set {
                this.pesoField = value;
            }
        }
        
        /// <remarks/>
        public string Cor {
            get {
                return this.corField;
            }
            set {
                this.corField = value;
            }
        }
        
        /// <remarks/>
        public string Raca {
            get {
                return this.racaField;
            }
            set {
                this.racaField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DataCadastro {
            get {
                return this.dataCadastroField;
            }
            set {
                this.dataCadastroField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Especie {
        
        private int idField;
        
        private string nomeField;
        
        private string descricaoField;
        
        private System.DateTime dataCadastroField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DataCadastro {
            get {
                return this.dataCadastroField;
            }
            set {
                this.dataCadastroField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Raca {
        
        private int idField;
        
        private string nomeField;
        
        private System.DateTime data_cadastroField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Data_cadastro {
            get {
                return this.data_cadastroField;
            }
            set {
                this.data_cadastroField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Animal_Cor {
        
        private int idField;
        
        private Animal animal_idField;
        
        private Cor cor_idField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public Animal Animal_id {
            get {
                return this.animal_idField;
            }
            set {
                this.animal_idField = value;
            }
        }
        
        /// <remarks/>
        public Cor Cor_id {
            get {
                return this.cor_idField;
            }
            set {
                this.cor_idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Cor {
        
        private int idField;
        
        private string nomeField;
        
        private System.DateTime data_cadastroField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Data_cadastro {
            get {
                return this.data_cadastroField;
            }
            set {
                this.data_cadastroField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Cliente_Animal {
        
        private int idField;
        
        private Animal animal_idField;
        
        private Cliente cliente_idField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public Animal Animal_id {
            get {
                return this.animal_idField;
            }
            set {
                this.animal_idField = value;
            }
        }
        
        /// <remarks/>
        public Cliente Cliente_id {
            get {
                return this.cliente_idField;
            }
            set {
                this.cliente_idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Cliente {
        
        private int idField;
        
        private string cPFField;
        
        private string rgField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string CPF {
            get {
                return this.cPFField;
            }
            set {
                this.cPFField = value;
            }
        }
        
        /// <remarks/>
        public string RG {
            get {
                return this.rgField;
            }
            set {
                this.rgField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void FazerLoginCompletedEventHandler(object sender, FazerLoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FazerLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FazerLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Usuario Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Usuario)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void inserirUsuarioCompletedEventHandler(object sender, inserirUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class inserirUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal inserirUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Usuario Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Usuario)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void listarUsuarioCompletedEventHandler(object sender, listarUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listarUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listarUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Usuario[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Usuario[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void alterarUsuarioCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void deletarUsuarioCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void inserirClienteCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void listarClienteCompletedEventHandler(object sender, listarClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listarClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listarClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Cliente[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Cliente[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void alterClienteCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void deletarClienteCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void inserirEspecieCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void listarEspecieCompletedEventHandler(object sender, listarEspecieCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listarEspecieCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listarEspecieCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Especie[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Especie[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void alterarEspecieCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void deletarEspecieCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void inserirAnimalCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void listarAnimalCompletedEventHandler(object sender, listarAnimalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listarAnimalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listarAnimalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Animal[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Animal[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void AlterarAnimalCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void deletarAnimalCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void inserirCorCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void listarCorCompletedEventHandler(object sender, listarCorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listarCorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listarCorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Cor[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Cor[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void AlterarCarCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void deletarCorCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void insertRacaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void listarRacaCompletedEventHandler(object sender, listarRacaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listarRacaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listarRacaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Raca[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Raca[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void AlterarRacaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void deletarRacaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void insertCliente_AnimalCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void listarCliente_AnimalCompletedEventHandler(object sender, listarCliente_AnimalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listarCliente_AnimalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listarCliente_AnimalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Cliente_Animal[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Cliente_Animal[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void insertAnimal_CorCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void listarAnimal_corCompletedEventHandler(object sender, listarAnimal_corCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listarAnimal_corCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listarAnimal_corCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Animal_Cor[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Animal_Cor[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void insertAnimal_RacaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void listarAnimal_RacaCompletedEventHandler(object sender, listarAnimal_RacaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listarAnimal_RacaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listarAnimal_RacaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Animal_Raca[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Animal_Raca[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591